#define WIFI_SSID "ADMIN"
#define WIFI_PASS "ADMIN1234"

#define SENSOR_READ_INTERVAL 10000
#define WED_DATALOG_INTERVAL 30000

#define FEEDER_DURATION 3000

#define TH_TEMP_HIGH 40
#define TH_TEMP_LOW  20
#define TH_PH_HIGH   10
#define TH_PH_LOW    4

#define FEEDER_TIME_1 6
#define FEEDER_TIME_2 18


/* Feeder On Times 
6AM
6PM
*/
